- name: Copy nginx config file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Enable configuration
  ansible.builtin.file:
    dest: /etc/nginx/sites-enabled/default
    src: /etc/nginx/sites-available/default
    state: link

- name: Copy index.html
  ansible.builtin.copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
