- name: Ensures {{ compose_location }} dir exists
  become: true
  ansible.builtin.file:
    path: "{{ compose_location }}"
    state: directory

- name: Ensures compose subdir exists
  become: true
  ansible.builtin.file:
    path: "{{ compose_location }}/{{ item.key }}"
    state: directory
  loop: "{{ nodes | dict2items }}"

- name: Copy docker compose
  become: true
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ compose_location }}/{{ item.key }}/docker-compose.yml"
  loop: "{{ nodes | dict2items }}"

- name: Create and start services
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ compose_location }}/{{ item.key }}"
    state: present
  loop: "{{ nodes | dict2items }}"
