- name: Copy server configuration files templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ minecraft_server_home }}/{{ item.dest }}"
  notify:
    - restart_mc_server
  loop:
    - { "src": "server.properties.j2", "dest": "server.properties" }
    - { "src": "ops.json.j2", "dest": "ops.json" }


- name: Copy plugins dir
  ansible.builtin.copy:
    src: plugins
    dest: "{{ minecraft_server_home }}"
  notify:
    - restart_mc_server
