- name: Copy ops template
  ansible.builtin.template:
    src: "ops.json.j2"
    dest: "{{ minecraft_server_home }}/ops.json"

- name: Copy server configuration file
  ansible.builtin.copy:
    src: "server.properties"
    dest: "{{ minecraft_server_home }}/"
    force: false

- name: Configure server.properties
  server_properties:
    file: "{{ minecraft_server_home }}/server.properties"
    server_settings: "{{ server_settings }}"
  notify:
    - restart_mc_server
  register: result

- name: Show updated server.properties
  ansible.builtin.debug:
    msg: "{{ result }}"
  when: result.changed
#  failed_when: true

- name: Copy plugins dir
  ansible.builtin.copy:
    src: plugins
    dest: "{{ minecraft_server_home }}"
  notify:
    - restart_mc_server
