- name: Install Java package (Ubuntu/Debian)
  ansible.builtin.apt:
    name: "{{ java_apt_package }}"
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'

- name: Copy server files to server dir
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ minecraft_server_home }}"
    mode: '0644'
  loop:
    - "{{ server_jar_file }}"
    - "{{ eula_txt_file }}"

- name: Copy entrypoint.sh.j2
  ansible.builtin.template:
    src: entrypoint.sh.j2
    dest: "{{ minecraft_server_home }}/entrypoint.sh"
    mode: '0744'

- name: Create minecraft systemd service file
  ansible.builtin.template:
    src: templates/minecraft.service.j2
    dest: /lib/systemd/system/minecraft.service
    mode: '0644'

- name: Start minecraft service
  ansible.builtin.systemd:
    name: minecraft
    state: started
    enabled: true
