- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
  tags:
    - install

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
  tags:
    - configure

- name: Backup
  ansible.builtin.include_tasks:
    file: backup.yml
    apply:
      become: true
  tags:
    - backup

- name: Restore
  ansible.builtin.include_tasks:
    file: restore.yml
    apply:
      become: true
  tags:
    - restore
    - never

