- name: Ensure service is stopped
  community.docker.docker_compose_v2:
    project_src: "{{ compose_location }}"
    state: stopped
  tags:
    - restore

- name: Delete old volumes content
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ grafana_data_volumes_dir }}"
    - "{{ grafana_config_host_data_dir }}"
  tags:
    - restore

- name: Unarchive storage tar backup
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "{{ storage_backup_tar }}", dest: "{{ grafana_volumes_dir }}"}
    - {src: "{{ config_backup_tar }}", dest: "{{ grafana_config_host_dir }}"}
  tags:
    - restore

- name: Set permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "472"
    recurse: true
  loop:
    - "{{ grafana_data_volumes_dir }}"
    - "{{ grafana_config_host_dir }}"
  tags:
    - restore

- name: Ensure service is restarted
  community.docker.docker_compose_v2:
    project_src: "{{ compose_location }}"
    state: present
  tags:
    - restore
