- name: Ensure service is stopped
  community.docker.docker_compose_v2:
    project_src: "{{ compose_location }}"
    state: stopped
  tags:
    - restore

- name: Delete old volumes content
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ storage_data_volume }}"
    - "{{ config_data_volume }}"
  tags:
    - restore

- name: Unarchive storage tar backup
  ansible.builtin.unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: "{{ storage_backup_tar }}", dest: "{{ storage_volume }}"}
    - {src: "{{ config_backup_tar }}", dest: "{{ config_volume }}"}
  tags:
    - restore

- name: Set permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "472"
    recurse: true
  loop:
    - "{{ storage_data_volume }}"
    - "{{ config_volume }}"
  tags:
    - restore

- name: Ensure service is restarted
  community.docker.docker_compose_v2:
    project_src: "{{ compose_location }}"
    state: present
  tags:
    - restore
