#!/usr/bin/env ansible-playbook
- name: Deploy grafana
  hosts: grafana

  roles:
    - role: grafana
      vars:
        domain_name: grafana.50thfloor.xyz
    - role: prometheus


- name: Deploy exporter nodes
  hosts: minecraft_servers

  roles:
    - role: node_exporter
