#!/usr/bin/env ansible-playbook
- name: Install jenkins
  hosts: wro_cat

  roles:
    - role: compose
      vars:
        compose_location: /home/jenkins
        compose_file: jenkins-docker-compose.yml.j2
        jenkins_image: jenkins/jenkins:lts-jdk17
