#!/usr/bin/env ansible-playbook
- name: Install jenkins agents
  hosts: cat

  roles:
    - role: jenkins_slaves
      vars:
        jenkins_url: http://10.10.1.103:8080
        nodes:
          agent_wro_1:
            image: wojtini397/50thagent:1.2
            agent_name: agent_wro_1
            port: 8024
            workDir: /home/jenkins
            secret: 13684e96ee25306695d479d15dc8e2204c5b2d6f9f3e807b6f862044ac7d8cbf
