#!/usr/bin/env ansible-playbook
- name: Deploy minecraft server
  hosts: minecraft_servers

  roles:
    - role: minecraft_server
      vars:
        server_jar_file: spigot-1.21.jar
        server_settings:
          motd: "Miłe Pogawędki on 50th floor"
          white-list: true
          difficulty: hard
          simulation-distance: 25
          view-distance: 32
          enable-rcon: false
          max-players: 10
    - role: node_exporter
