#!/usr/bin/env ansible-playbook
- name: Deploy grafana
  hosts: wro_cat

  roles:
    - role: grafana
      vars:
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://192.168.1.103:9090
            isDefault: true
            access: proxy
            editable: true
    - role: prometheus

- name: Deploy nodes
  hosts: all

  roles:
    - role: node_exporter