#!/usr/bin/env ansible-playbook
- name: Deploy nginx dns
  hosts: wro_cat

  roles:
    - role: nginx_rp
      vars:
        letsencrypt_email: wmaziarzw@gmail.com
        domain_name: 50thfloor.xyz
        subdomains:
          grafana:
            prefix: grafana.
            upstream: 192.168.1.103:3000
