#!/usr/bin/env ansible-playbook
- name: Install YouTrack
  hosts: wro_cat

  roles:
    - role: compose
      vars:
        compose_location: /home/youtrack
        compose_file: youtrack-docker-compose.yml.j2
        youtrack_image: jetbrains/youtrack:2024.2.38971
