- name: Install letsencrypt
  ansible.builtin.apt:
    name: letsencrypt
    state: latest

- name: Create letsencrypt directory
  ansible.builtin.file:
    name: "{{ letsencrypt_dir }}"
    state: directory

- name: Install nginx site for letsencrypt requests
  ansible.builtin.template:
    src: lets_encrypt.nginx.conf.j2
    dest: /etc/nginx/sites-available/certbot

- name: Enable configuration
  ansible.builtin.file:
    src: /etc/nginx/sites-available/certbot
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Reload nginx to activate letsencrypt site
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Create letsencrypt certificate
  ansible.builtin.shell: letsencrypt certonly -n --webroot -w {{ letsencrypt_dir }} -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}
