grafana_storage_dir: /var/lib/grafana
grafana_config_dir: /etc/grafana

docker_volumes_dir: /var/lib/docker/volumes
storage_volume: "{{ docker_volumes_dir }}/grafana_storage"
storage_data_volume: "{{ storage_volume }}/_data"

config_volume: "{{ docker_volumes_dir }}/grafana_config"
config_data_volume: "{{ config_volume }}/_data"
config_datasources_dir: "{{ config_data_volume }}/provisioning/datasources"


backups:
  - { dir: "{{ storage_data_volume }}", name: "grafana_storage_backup.tar" }
  - { dir: "{{ config_data_volume }}", name: "grafana_config_backup.tar" }