- name: Set deploy dir
  delegate_to: localhost
  set_fact:
    deploy_dir: "{{ instances_dir }}/{{ instance_name }}"
    templates_dir: "{{ role_path }}/templates"
    source_dir: "{{ role_path }}/templates/{{ instance_config.project_dir }}"

- name: Combine source_dir with bonus files
  delegate_to: localhost
  set_fact:
    combined_source_dirs: >-
      {{ [source_dir] + (instance_config.bonus | map('regex_replace', '^(.*)$', templates_dir ~ '/\1') | list) }}

- name: Initialize all found files list
  delegate_to: localhost
  become: false
  find:
    paths: "{{ file }}"
    file_type: file
    recurse: true
  register: all_files_arr
  loop: "{{ combined_source_dirs }}"
  loop_control:
    loop_var: file

- name: Combine all found files into one list
  set_fact:
    all_files: "{{ all_files_arr.results | map(attribute='files') | sum(start=[]) }}"

- name: Map source files to flattened deploy paths (drop 1st subdir)
  set_fact:
    file_target_map: "{{ file_target_map | default({}) | combine({ file.path: deploy_dir + '/' + (file.path | regex_replace('^' ~ templates_dir ~ '/[^/]+/', '')) | regex_replace('\\.j2$', '') }) }}"
  loop: "{{ all_files }}"
  loop_control:
    loop_var: file

- name: Separate Jinja2 templates from static files
  set_fact:
    j2_files: "{{ file_target_map | dict2items | selectattr('key', 'search', '\\.j2$') | list }}"
    static_files: "{{ file_target_map | dict2items | rejectattr('key', 'search', '\\.j2$') | list }}"

- name: Show value of a variable
  delegate_to: localhost
  debug:
    msg:
      normal: "{{ static_files }}"
      j2: "{{ j2_files }}"

- name: Create dir
  file:
    path: "{{ deploy_dir }}"
    state: directory

- name: Ensure target directories exist
  file:
    path: "{{ item.value | dirname }}"
    state: directory
    mode: '0755'
  loop: "{{ file_target_map | dict2items }}"

- name: Render Jinja2 templates
  template:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
    mode: '0644'
  loop: "{{ j2_files }}"
  register: j2_render

- name: Copy static files
  copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
    mode: '0644'
  loop: "{{ static_files }}"
  register: non_j2_copy

- name: Check if any file changed
  set_fact:
    any_changed: "{{ (j2_render.results | selectattr('changed') | list) | length > 0 or (non_j2_copy.results | selectattr('changed') | list) | length > 0 }}"

- name: Start docker compose
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_dir }}"
    state: present
    recreate: always
    remove_orphans: true
  when: any_changed
