- name: Cleanup removed apps
  ansible.builtin.include_tasks:
    file: cleanup.yml
  tags:
    - cleanup

- name: Install apps
  include_tasks: install.yml
  loop: "{{ instances | dict2items }}"
  loop_control:
    label: "{{ app.key }}"
    loop_var: app
  vars:
    instance_name: "{{ app.key }}"
    instance_config: "{{ app.value }}"
