#!/usr/bin/env ansible-playbook
- name: Deploy containers
  hosts: prod01
  become: true
  roles:
    - instance
  vars:
    instances:
      pihole:
        projects:
          - pihole
        pihole_image: pihole/pihole:latest
        pihole_password: mateusz
