#!/usr/bin/env ansible-playbook
- name: Deploy containers
  hosts: test01
  become: true
  roles:
    - instance
  vars_files:
    - secrets/test.yml
  vars:
    instances:
      anotehr_app:
        projects:
          - aaa
        hw_port: 8075
