#!/usr/bin/env ansible-playbook
- name: Deploy containers
  hosts: test01
  become: true
  roles:
    - instance
  vars:
    instances:
      web-app-test:
        project_dir: hello-world-web-app
        test_value: testownik
        bonus: []
